---
- hosts: all
  remote_user: xoma
  become: yes
  vars:
    project_name: didactic-adventure
    project_dir: "{{ playbook_dir }}/.."
    work_dir: "/srv/{{ project_name }}"
    user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    # - name: Ensure java installed
    #   yum:
    #     name: java-1.8.0-openjdk
    #     state: latest

    # - name: Ensure work dir exists
    #   file:
    #     path: "{{ work_dir }}"
    #     state: directory

    - name: Ensure systemd unit installed
      template:
        src: didactic-adventure.service.j2
        dest: "/etc/systemd/system/{{ project_name }}.service"

    - name: Build project
      shell: "lein uberjar"
      args:
        chdir: "{{ project_dir }}"
      become: false
      delegate_to: 127.0.0.1

    - name: Deployment
      copy:
        dest: "{{ work_dir }}/{{ project_name }}.jar"
        src: "{{ project_dir }}/target/uberjar/{{ project_name }}-0.1.0-SNAPSHOT-standalone.jar"
        group: nobody

    - name: Run
      systemd:
        name: "{{ project_name }}"
        state: restarted
